/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SimpleText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type ArticleBody = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  _key: string;
} & PullQuote>;

export type PullQuote = {
  _type: "pullQuote";
  text: string;
  attribution?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  socials?: Array<{
    platform: "instagram" | "tiktok" | "linkedin" | "whatsapp";
    url: string;
    _type: "socialProfile";
    _key: string;
  }>;
  organization?: {
    legalName?: string;
    foundingDate?: string;
    address?: {
      streetAddress?: string;
      postalCode?: string;
      addressLocality?: string;
      addressCountry?: string;
    };
  };
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  milestones?: Array<{
    period: string;
    title: string;
    description?: string;
    image?: ImageWithAlt;
    _type: "milestone";
    _key: string;
  }>;
  offices?: Array<{
    scope: "italy" | "international";
    title: string;
    description?: string;
    location?: string;
    email: string;
    _type: "office";
    _key: string;
  }>;
  documents?: Array<{
    title: string;
    file: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    updatedYear?: number;
    _type: "foundationDocument";
    _key: string;
  }>;
};

export type NewsPostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "newsPost";
};

export type NewsPage = {
  _id: string;
  _type: "newsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  featuredPost?: NewsPostReference;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  stats?: Array<{
    value: string;
    label: string;
    description?: string;
    _type: "stat";
    _key: string;
  }>;
  statsAsOf?: string;
};

export type Group = {
  _id: string;
  _type: "group";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  city: string;
  slug: Slug;
  kind: "local" | "project";
  country: string;
  region?: string;
  location: Geopoint;
  description?: InternationalizedArrayText;
  email?: string;
  whatsappUrl?: string;
  featured?: boolean;
  photo?: ImageWithAlt;
  volunteerCount?: string;
  projectCount?: number;
};

export type InternationalizedArrayText = Array<{
  _key: string;
} & InternationalizedArrayTextValue>;

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
  language: string;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<{
  _key: string;
} & InternationalizedArrayReferenceValue>;

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: NewsPostReference | ProjectReference;
  language: string;
};

export type NewsPost = {
  _id: string;
  _type: "newsPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title: string;
  slug: Slug;
  excerpt: string;
  publishedAt: string;
  author?: string;
  category: "field-stories" | "new-locations" | "medical" | "culture";
  project?: ProjectReference;
  coverImage: ImageWithAlt;
  body: ArticleBody;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title: string;
  slug: Slug;
  sortOrder?: number;
  teaser: string;
  headline: string;
  headlineEmphasis?: string;
  summary?: string;
  intro?: string;
  body?: SimpleText;
  partners?: Array<string>;
  coverImage: ImageWithAlt;
  heroImage?: ImageWithAlt;
  showcasePhotos?: Array<{
    _key: string;
  } & ImageWithAlt>;
  gallery?: Array<{
    _key: string;
  } & ImageWithAlt>;
  activities?: Array<{
    label: string;
    icon: "book-open" | "calendar" | "droplet" | "globe" | "graduation-cap" | "heart-handshake" | "hospital" | "languages" | "leaf" | "megaphone" | "puzzle" | "recycle" | "siren" | "stethoscope" | "tent" | "users";
    _type: "activity";
    _key: string;
  }>;
  resources?: Array<{
    kind: "book" | "document" | "video";
    title: string;
    description?: string;
    shortDescription?: string;
    cover?: ImageWithAlt;
    file?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    url?: string;
    _type: "resource";
    _key: string;
  }>;
  startedYear?: number;
  impact?: Array<{
    value: string;
    label: string;
    description?: string;
    _type: "impactFigure";
    _key: string;
  }>;
  outcomes?: SimpleText;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes = SimpleText | ArticleBody | PullQuote | SanityImageAssetReference | ImageWithAlt | SiteSettings | SanityFileAssetReference | AboutPage | NewsPostReference | NewsPage | HomePage | Group | InternationalizedArrayText | Geopoint | Slug | InternationalizedArrayTextValue | TranslationMetadata | InternationalizedArrayReference | ProjectReference | InternationalizedArrayReferenceValue | NewsPost | Project | SanityImageCrop | SanityImageHotspot | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: NEWS_INDEX_QUERY
// Query: {	"featured": coalesce(		*[_id == "newsPage-" + $locale][0].featuredPost->{	_id,	title,	"slug": slug.current,	excerpt,	category,	publishedAt,	author,	coverImage,	"readingMinutes": math::max([		1,		round(length(pt::text(body)) / select(language == "ja" => 500, 1000))	])},		*[_type == "newsPost" && language == $locale] | order(publishedAt desc)[0]{	_id,	title,	"slug": slug.current,	excerpt,	category,	publishedAt,	author,	coverImage,	"readingMinutes": math::max([		1,		round(length(pt::text(body)) / select(language == "ja" => 500, 1000))	])}	),	"posts": *[_type == "newsPost" && language == $locale && defined(slug.current)]		| order(publishedAt desc){	_id,	title,	"slug": slug.current,	excerpt,	category,	publishedAt,	author,	coverImage,	"readingMinutes": math::max([		1,		round(length(pt::text(body)) / select(language == "ja" => 500, 1000))	])}}
export type NEWS_INDEX_QUERY_RESULT = {
  featured: {
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    category: "culture" | "field-stories" | "medical" | "new-locations";
    publishedAt: string;
    author: string | null;
    coverImage: ImageWithAlt;
    readingMinutes: number | 1;
  } | null;
  posts: Array<{
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    category: "culture" | "field-stories" | "medical" | "new-locations";
    publishedAt: string;
    author: string | null;
    coverImage: ImageWithAlt;
    readingMinutes: number | 1;
  }>;
};

// Source: ../web/src/lib/sanity/queries.ts
// Variable: NEWS_POST_QUERY
// Query: *[_type == "newsPost" && language == $locale && slug.current == $slug][0]{			_id,	title,	"slug": slug.current,	excerpt,	category,	publishedAt,	author,	coverImage,	"readingMinutes": math::max([		1,		round(length(pt::text(body)) / select(language == "ja" => 500, 1000))	]),		_updatedAt,		body,		"project": project->{ title, teaser, "slug": slug.current },		"translations": coalesce(	*[_type == "translation.metadata" && references(^._id)][0].translations[].value->{		language, "slug": slug.current	},	[{ language, "slug": slug.current }])	}
export type NEWS_POST_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  category: "culture" | "field-stories" | "medical" | "new-locations";
  publishedAt: string;
  author: string | null;
  coverImage: ImageWithAlt;
  readingMinutes: number | 1;
  _updatedAt: string;
  body: ArticleBody;
  project: {
    title: string;
    teaser: string;
    slug: string;
  } | null;
  translations: Array<{
    language: string | null;
    slug: string;
  }> | Array<{
    language: string | null;
    slug: string;
  } | null>;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: RELATED_POSTS_QUERY
// Query: *[_type == "newsPost" && language == $locale && _id != $id]{			_id,	title,	"slug": slug.current,	excerpt,	category,	publishedAt,	author,	coverImage,	"readingMinutes": math::max([		1,		round(length(pt::text(body)) / select(language == "ja" => 500, 1000))	]),		"score": select(defined($projectSlug) && project->slug.current == $projectSlug => 2, 0)			+ select(category == $category => 1, 0)	} | order(score desc, publishedAt desc)[0...3]
export type RELATED_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  category: "culture" | "field-stories" | "medical" | "new-locations";
  publishedAt: string;
  author: string | null;
  coverImage: ImageWithAlt;
  readingMinutes: number | 1;
  score: 0 | 1 | 2 | 3;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: PROJECT_NEWS_QUERY
// Query: *[_type == "newsPost" && language == $locale && project->slug.current == $projectSlug]		| order(publishedAt desc)[0...3]{	_id,	title,	"slug": slug.current,	excerpt,	category,	publishedAt,	author,	coverImage,	"readingMinutes": math::max([		1,		round(length(pt::text(body)) / select(language == "ja" => 500, 1000))	])}
export type PROJECT_NEWS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  category: "culture" | "field-stories" | "medical" | "new-locations";
  publishedAt: string;
  author: string | null;
  coverImage: ImageWithAlt;
  readingMinutes: number | 1;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{		"socials": socials[]{ _key, platform, url },		organization{ legalName, foundingDate, address }	}
export type SITE_SETTINGS_QUERY_RESULT = {
  socials: null;
  organization: null;
} | {
  socials: Array<{
    _key: string;
    platform: "instagram" | "linkedin" | "tiktok" | "whatsapp";
    url: string;
  }> | null;
  organization: {
    legalName: string | null;
    foundingDate: string | null;
    address: {
      streetAddress?: string;
      postalCode?: string;
      addressLocality?: string;
      addressCountry?: string;
    } | null;
  } | null;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: {	"projects": *[_type == "project" && language == $locale && defined(slug.current)]		| order(sortOrder asc){			_id,			title,			"slug": slug.current,			teaser,			coverImage		},	"stats": *[_id == "homePage-" + $locale][0].stats[]{ _key, value, label, description },	"statsAsOf": *[_id == "homePage-" + $locale][0].statsAsOf}
export type HOME_PAGE_QUERY_RESULT = {
  projects: Array<{
    _id: string;
    title: string;
    slug: string;
    teaser: string;
    coverImage: ImageWithAlt;
  }>;
  stats: Array<{
    _key: string;
    value: string;
    label: string;
    description: string | null;
  }> | null;
  statsAsOf: null | string;
};

// Source: ../web/src/lib/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_id == "aboutPage-" + $locale][0]{		"stats": *[_id == "homePage-" + $locale][0].stats[]{ _key, value, label },		"statsAsOf": *[_id == "homePage-" + $locale][0].statsAsOf,		"milestones": milestones[]{ _key, period, title, description, image },		"offices": offices[]{ _key, scope, title, description, location, email },		"documents": documents[defined(file.asset)]{			_key,			title,			updatedYear,			"href": file.asset->url,			"format": upper(file.asset->extension)		}	}
export type ABOUT_PAGE_QUERY_RESULT = {
  stats: Array<{
    _key: string;
    value: string;
    label: string;
  }> | null;
  statsAsOf: null | string;
  milestones: null;
  offices: null;
  documents: null;
} | {
  stats: Array<{
    _key: string;
    value: string;
    label: string;
  }> | null;
  statsAsOf: null | string;
  milestones: Array<{
    _key: string;
    period: string;
    title: string;
    description: string | null;
    image: ImageWithAlt | null;
  }> | null;
  offices: Array<{
    _key: string;
    scope: "international" | "italy";
    title: string;
    description: string | null;
    location: string | null;
    email: string;
  }> | null;
  documents: Array<{
    _key: string;
    title: string;
    updatedYear: number | null;
    href: string;
    format: string;
  }> | null;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: PROJECT_SHOWCASE_QUERY
// Query: *[_type == "project" && language == $locale && defined(slug.current)] | order(sortOrder asc){		_id,		title,		"slug": slug.current,		teaser,		showcasePhotos	}
export type PROJECT_SHOWCASE_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  teaser: string;
  showcasePhotos: Array<{
    _key: string;
  } & ImageWithAlt> | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && language == $locale && slug.current == $slug][0]{		_id,		title,		"slug": slug.current,		headline,		headlineEmphasis,		summary,		teaser,		intro,		body,		heroImage,		coverImage,		gallery,		activities,		"resources": resources[]{			_key,			kind,			title,			description,			shortDescription,			cover,			"href": coalesce(url, file.asset->url)		},		partners,		startedYear,		"impact": impact[]{ _key, value, label, description },		outcomes,		_updatedAt,		"translations": coalesce(	*[_type == "translation.metadata" && references(^._id)][0].translations[].value->{		language, "slug": slug.current	},	[{ language, "slug": slug.current }])	}
export type PROJECT_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  headline: string;
  headlineEmphasis: string | null;
  summary: string | null;
  teaser: string;
  intro: string | null;
  body: SimpleText | null;
  heroImage: ImageWithAlt | null;
  coverImage: ImageWithAlt;
  gallery: Array<{
    _key: string;
  } & ImageWithAlt> | null;
  activities: Array<{
    label: string;
    icon: "book-open" | "calendar" | "droplet" | "globe" | "graduation-cap" | "heart-handshake" | "hospital" | "languages" | "leaf" | "megaphone" | "puzzle" | "recycle" | "siren" | "stethoscope" | "tent" | "users";
    _type: "activity";
    _key: string;
  }> | null;
  resources: Array<{
    _key: string;
    kind: "book" | "document" | "video";
    title: string;
    description: string | null;
    shortDescription: string | null;
    cover: ImageWithAlt | null;
    href: string | null;
  }> | null;
  partners: Array<string> | null;
  startedYear: number | null;
  impact: Array<{
    _key: string;
    value: string;
    label: string;
    description: string | null;
  }> | null;
  outcomes: SimpleText | null;
  _updatedAt: string;
  translations: Array<{
    language: string | null;
    slug: string;
  }> | Array<{
    language: string | null;
    slug: string;
  } | null>;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: CONTACT_EMAIL_QUERY
// Query: coalesce(		*[_id == "aboutPage-" + $locale][0].offices[scope == "international"][0].email,		*[_id == "aboutPage-" + $locale][0].offices[0].email	)
export type CONTACT_EMAIL_QUERY_RESULT = string | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: GROUPS_QUERY
// Query: {	"groups": *[_type == "group" && defined(slug.current)] | order(city asc){		_id,		"id": slug.current,		city,		region,		country,		kind,		"lat": location.lat,		"lng": location.lng,		"description": coalesce(			description[language == $locale][0].value,			description[language == "en"][0].value		),		email,		whatsappUrl,		featured,		photo,		volunteerCount,		projectCount	},	"offices": *[_id == "aboutPage-" + $locale][0].offices[]{ scope, email }}
export type GROUPS_QUERY_RESULT = {
  groups: Array<{
    _id: string;
    id: string;
    city: string;
    region: string | null;
    country: string;
    kind: "local" | "project";
    lat: number | null;
    lng: number | null;
    description: string | null;
    email: string | null;
    whatsappUrl: string | null;
    featured: boolean | null;
    photo: ImageWithAlt | null;
    volunteerCount: string | null;
    projectCount: number | null;
  }>;
  offices: Array<{
    scope: "international" | "italy";
    email: string;
  }> | null;
};

// Source: ../web/src/lib/sanity/queries.ts
// Variable: SITEMAP_QUERY
// Query: {	"documents": *[_type in ["newsPost", "project"] && defined(slug.current)]{		_type,		language,		"slug": slug.current,		_updatedAt,		"translationGroup": coalesce(*[_type == "translation.metadata" && references(^._id)][0]._id, _id)	}}
export type SITEMAP_QUERY_RESULT = {
  documents: Array<{
    _type: "newsPost";
    language: string | null;
    slug: string;
    _updatedAt: string;
    translationGroup: string;
  } | {
    _type: "project";
    language: string | null;
    slug: string;
    _updatedAt: string;
    translationGroup: string;
  }>;
};

