export { default as ProjectsSection } from './projects-section.svelte';
export { default as ProjectCard } from './project-card.svelte';
export { projects, type Project } from './projects';
export { type ProjectId } from './projects';
export { projectDetails, getProjectDetail, type ProjectDetail } from './project-details';
export { default as ProjectHeader } from './detail/project-header.svelte';
export { default as ProjectOverview } from './detail/project-overview.svelte';
export { default as ProjectNews } from './detail/project-news.svelte';
export { default as ProjectResources } from './detail/project-resources.svelte';
export { default as ProjectPartners } from './detail/project-partners.svelte';
